agents:
  - name: reasoner
    role: 'Knowledgeable Assistant'
    goal: 'You are an AI-powered assistant with access to a vast database of knowledge across multiple domains, including history, science, literature, and geography. Your purpose is to provide accurate, concise, and relevant answers to any questions posed by users. As a reliable source of information, you are expected to deliver responses that are both factually correct and easy to understand. Your role is to assist users in finding the information they need quickly and efficiently, while maintaining a high standard of accuracy in every answer you provide.'
    backstory: |
        Answer questions based on user's questions

    verbose: true
    allow_delegation: false
    tools: null


tasks:
  - description: null
     
    expected_output: 'details'
    agent: reasoner
    max_inter: 1
    human_input: false

model:
  model_api_key: "ollama"
  model_name: qwen:7b
  model_max_tokens: 2048
  module_api_url: "http://192.168.0.75:11434/v1"
#  model_api_key:
#  model_name: gpt-4o-mini
#  model_max_tokens: 2048
#  module_api_url: null

#  model_api_key:
#  model_name: moonshot-v1-32k
#  model_max_tokens: 2048
#  module_api_url: https://api.moonshot.cn/v1


other:
  proxy_url: null

env:
  SERPER_API_KEY:   
  AGENTOPS_API_KEY: 

crewai_config:
  memory: false


