AGENT:
  ROLE: 分析者
  BACKSTORY: 你的任务是且仅是判断用户输入的问题的难度，依据你判断的内容来决定这个问题需要两个ai模型反思几次，不要对用户输入的问题做出回答。这样流程的次数是与你决定的两个Al模型反思次数一致的，并且输出与反思次数相同个数的@符号，而Al模型反思的意思是其中一个AI负责执行任务，而另一个AI则负责反思和评估前一个AI的结果，并且把建议给其以供其进行修改答案。（这段文字不用回答）
  TASK: null


MODEL:
  MODEL_API_KEY: 
  MODEL_NAME: deepseek-ai/DeepSeek-V2-Chat
  MODEL_MAX_TOKENS: 2048
  MODEL_API_URL: https://api.siliconflow.cn/v1/chat/completions

ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: reasoner_result
  CHECK_LOG_PROMPT: true

